apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mongo.yaml
  - redis.yaml
  - rabbitmq.yaml
  - gateway.yaml
  - realtime.yaml
  - sim-engine.yaml
  - event-orchestrator.yaml
  - quest-ai.yaml
  - progression.yaml
  - ingress.yaml
images:
  - name: ghcr.io/your-org/reality-gateway
    newTag: latest
  - name: ghcr.io/your-org/reality-realtime
    newTag: latest
  - name: ghcr.io/your-org/reality-sim-engine
    newTag: latest
  - name: ghcr.io/your-org/reality-event-orchestrator
    newTag: latest
  - name: ghcr.io/your-org/reality-quest-ai
    newTag: latest
  - name: ghcr.io/your-org/reality-progression
    newTag: latest
configMapGenerator:
  - name: reality-env
    literals:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGO_URL=mongodb://mongo:27017/reality
      - REDIS_URL=redis://redis:6379
      - PORT_GATEWAY=8080
      - PORT_REALTIME=8090
secretGenerator:
  - name: reality-secrets
    literals:
      - JWT_SECRET=change-me
      - OPENAI_API_KEY=
generatorOptions:
  disableNameSuffixHash: true
